# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e15b5d01b81f3e69905f572c9fb8b59e7118906e2bfda49c93adc32f37b401ba382a8bb33c9daa44d837666b0fb0625d4f2a1e5852c01929a0044ab7d8679c1

test:
  secret_key_base: d8d5efa081b0301c560a38ad75058027f1a6171a4dc62e38a970a4f0edea4945331b6681361e42933d0394e7b980b8c1a19b0184f4cd1fa3c4f6e643041e42c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
